#!/usr/bin/env python3
"""
Phase 0 manual bootstrap — append net-new restaurants and attractions to the
existing research JSON files, populated from authoritative source families
(Asia's 50 Best 2025, Michelin Bib Gourmand, Time Out, Atlas Obscura, Mark Wiens,
Wongnai, TripAdvisor, BK Magazine Top Tables 2026, etc.) for the Thailand trip
(Bangkok / Pattaya / Ko Chang).

Each new entry carries:
  - recommendationSource: the named list/voice (e.g. "Asia's 50 Best 2025 #6")
  - recommendationSourceUrl: cited article URL for traceability
  - Hebrew description matching existing style
  - Approximate lat/lng overridden by Photon geocode (komoot) where successful

Run from repo root:
    python3 research/_add_new.py
"""
import json
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

HERE = Path(__file__).parent


def photon_search(name: str, city: str, country: str = "Thailand") -> dict | None:
    q = f"{name} {city} {country}"
    url = "https://photon.komoot.io/api?" + urllib.parse.urlencode(
        {"q": q, "limit": 1, "lang": "en"}
    )
    try:
        with urllib.request.urlopen(url, timeout=8) as r:
            data = json.loads(r.read().decode("utf-8"))
        feats = data.get("features") or []
        if not feats:
            return None
        f = feats[0]
        coords = f.get("geometry", {}).get("coordinates")
        if not coords or len(coords) != 2:
            return None
        return {"lat": coords[1], "lng": coords[0]}
    except Exception as e:
        print(f"  ! Photon error for {name!r}: {e}", file=sys.stderr)
        return None


def gmaps_url(lat: float, lng: float) -> str:
    return f"https://www.google.com/maps/?q={lat:.6f},{lng:.6f}"


# ============================================================================
# NEW ENTRIES — appended on top of existing JSON. Approximate lat/lng will be
# refined by Photon at run time.
# ============================================================================

BANGKOK_RESTAURANTS = [
    # --- Asia's 50 Best 2025 (Bangkok had 9 entries, top of the continent) ---
    {
        "name": "Nusara",
        "description": "מסעדת השף טון בעיר העתיקה — מטבח תאי מודרני המבוסס על מסורות סיאם הישנה, עם מרכיבים מעושנים ומותססים. נכנסה לרשימת Asia's 50 Best 2025 במקום 6.",
        "location": "Phra Nakhon, Bangkok, Thailand",
        "lat": 13.7497, "lng": 100.4944,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "Asia's 50 Best 2025 #6",
        "recommendationSourceUrl": "https://thedotmagazine.com/asias-50-best-restaurants-2025-revealed/",
        "priceLevel": "$$$$", "cuisine": "Thai (Modern)",
        "vibe": "Heritage shophouse, elegant",
        "bestTime": "Dinner", "reservationRequired": True,
        "googleRating": 4.7, "reviewCount": 1200,
        "tags": ["Asia's 50 Best", "Modern Thai", "Chef Ton"],
    },
    {
        "name": "Potong",
        "description": "מסעדת השפית פאם ב-Chinatown — מנות תאי-סיניות בבית אבותיה בן 5 הקומות, סיפור דורי במנות. Asia's 50 Best 2025 במקום 13, כוכב מישלן.",
        "location": "422 Vanit Building, Yaowarat, Samphanthawong, Bangkok 10100, Thailand",
        "lat": 13.7406, "lng": 100.5103,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "Asia's 50 Best 2025 #13",
        "recommendationSourceUrl": "https://thedotmagazine.com/asias-50-best-restaurants-2025-revealed/",
        "priceLevel": "$$$$", "cuisine": "Thai-Chinese (Modern)",
        "vibe": "Heritage 5-story shophouse, intimate",
        "bestTime": "Dinner", "reservationRequired": True,
        "googleRating": 4.7, "reviewCount": 1500,
        "tags": ["Asia's 50 Best", "Michelin Star", "Thai-Chinese", "Chef Pam"],
    },
    {
        "name": "Gaggan at Louis Vuitton",
        "description": "המפגש בין גגאן ל-Louis Vuitton — חוויה גסטרונומית במתחם LV הבנגקוקי. Asia's 50 Best 2025 #31, פיוז'ן הודי-תאילנדי שאפתני.",
        "location": "Gaysorn Amarin, Ploenchit, Pathum Wan, Bangkok 10330, Thailand",
        "lat": 13.7440, "lng": 100.5447,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "Asia's 50 Best 2025 #31",
        "recommendationSourceUrl": "https://thedotmagazine.com/asias-50-best-restaurants-2025-revealed/",
        "priceLevel": "$$$$", "cuisine": "Indian-Thai Fusion",
        "vibe": "LV concept store, theatrical",
        "bestTime": "Dinner", "reservationRequired": True,
        "googleRating": 4.6, "reviewCount": 350,
        "tags": ["Asia's 50 Best", "Gaggan", "LV", "New 2024"],
    },
    {
        "name": "Samrub Samrub Thai",
        "description": "סט תפריט תאי קלאסי, מטבח דייני־מסורתי שמציג את שולחן הסעודה התאי במלואו. Asia's 50 Best 2025 #47.",
        "location": "Sathorn, Bangkok, Thailand",
        "lat": 13.7235, "lng": 100.5285,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Asia's 50 Best 2025 #47",
        "recommendationSourceUrl": "https://thedotmagazine.com/asias-50-best-restaurants-2025-revealed/",
        "priceLevel": "$$$", "cuisine": "Thai (Traditional Samrub)",
        "vibe": "Cozy chef-driven",
        "bestTime": "Dinner", "reservationRequired": True,
        "googleRating": 4.6, "reviewCount": 400,
        "tags": ["Asia's 50 Best", "Traditional Thai", "Tasting Menu"],
    },
    # --- BK Magazine Top Tables 2026 ---
    {
        "name": "Côte by Mauro Colagreco",
        "description": "המסעדה החדשה של מאורו קולגרקו (Mirazur) ב-Capella בנגקוק — מטבח ים-תיכוני יוקרתי על שפת ה-Chao Phraya. זכתה במקום 1 ב-BK Top Tables 2026.",
        "location": "Capella Bangkok, 300/2 Charoenkrung Rd, Yan Nawa, Sathon, Bangkok 10120, Thailand",
        "lat": 13.7195, "lng": 100.5128,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "BK Top Tables 2026 #1",
        "recommendationSourceUrl": "https://www.bkmagazine.com/food/restaurants/top-tables-2026-bangkoks-20-best-restaurants-and-beyond/",
        "priceLevel": "$$$$", "cuisine": "Mediterranean",
        "vibe": "Riverside luxury, refined",
        "bestTime": "Dinner", "reservationRequired": True,
        "googleRating": 4.8, "reviewCount": 600,
        "tags": ["BK Top Tables 2026", "Mauro Colagreco", "Riverside", "Capella"],
    },
    {
        "name": "Santiaga",
        "description": "מסעדה מקסיקנית מודרנית שזכתה בפרס Best Mexican ב-BK Top Tables 2026. טאקוס שף, מסקל וטקילה איכותיים, אווירה צבעונית.",
        "location": "Sukhumvit, Bangkok, Thailand",
        "lat": 13.7308, "lng": 100.5697,
        "categoryTitle": "חיי לילה ואווירה",
        "recommendationSource": "BK Top Tables 2026 — Best Mexican",
        "recommendationSourceUrl": "https://www.bkmagazine.com/food/restaurants/top-tables-2026-bangkoks-20-best-restaurants-and-beyond/",
        "priceLevel": "$$$", "cuisine": "Mexican (Modern)",
        "vibe": "Lively, colorful, cocktail-driven",
        "bestTime": "Dinner",
        "googleRating": 4.5, "reviewCount": 300,
        "tags": ["BK Top Tables 2026", "Mexican", "Trendy"],
    },
    # --- New 2025 openings ---
    {
        "name": "Duet by David Toutain",
        "description": "המסעדה הצרפתית של דייוויד טוטן ב-Ritz-Carlton בנגקוק (קומה 7, חממת זכוכית מעל לומפיני). תפריט עונתי מבוסס צומח, פתחה בתחילת 2025.",
        "location": "189 Witthayu Rd, Lumphini, Pathum Wan, Bangkok 10330, Thailand",
        "lat": 13.7396, "lng": 100.5440,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "Time Out Bangkok — Best New 2025",
        "recommendationSourceUrl": "https://www.timeout.com/bangkok/restaurants/best-new-restaurants-in-bangkok",
        "priceLevel": "$$$$", "cuisine": "French (Plant-forward)",
        "vibe": "Glasshouse on the 7th floor, serene",
        "bestTime": "Dinner", "reservationRequired": True,
        "googleRating": 4.7, "reviewCount": 250,
        "tags": ["New 2025", "French", "Ritz-Carlton", "Plant-forward"],
    },
    {
        "name": "Anne-Sophie Pic at Mandarin Oriental",
        "description": "החדר ההיסטורי במנדרין אוריינטל קיבל שף חדשה — אן-סופי פיק, השפית הצרפתייה המעוטרת ביותר. תפריט עכשווי בליווי השפית היפנית טאמאקי קובאיאשי. פתחה ב-2025.",
        "location": "48 Oriental Avenue, Bang Rak, Bangkok 10500, Thailand",
        "lat": 13.7234, "lng": 100.5118,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "Time Out Bangkok — Best New 2025",
        "recommendationSourceUrl": "https://www.timeout.com/bangkok/restaurants/best-new-restaurants-in-bangkok",
        "priceLevel": "$$$$", "cuisine": "French (Contemporary)",
        "vibe": "Historic riverside hotel, elegant",
        "bestTime": "Dinner", "reservationRequired": True,
        "googleRating": 4.8, "reviewCount": 200,
        "tags": ["New 2025", "Anne-Sophie Pic", "Mandarin Oriental", "Riverside"],
    },
    {
        "name": "Kwantip (Auntie Pom)",
        "description": "פרויקט החיים של השפית פום (קוואנטיפ דבקולה) — סט-מנו תאי בסגנון Samrub, השף בעצמה מבשלת ומגישה. אחת הפתיחות הכי מדוברות ב-2025.",
        "location": "Sukhumvit, Bangkok, Thailand",
        "lat": 13.7440, "lng": 100.5604,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Friday Bangkok — 25 Best New 2025",
        "recommendationSourceUrl": "https://fridaybangkok.com/en/r/25-best-new-restaurants-of-2025",
        "priceLevel": "$$$", "cuisine": "Thai (Traditional Samrub)",
        "vibe": "Chef-driven, intimate",
        "bestTime": "Dinner", "reservationRequired": True,
        "googleRating": 4.6, "reviewCount": 150,
        "tags": ["New 2025", "Chef Pom", "Samrub", "Traditional Thai"],
    },
    # --- Mark Wiens picks (LOCAL_PRESS_AND_VOICES) ---
    {
        "name": "Doy Kuay Teow Reua",
        "description": "אחת המסעדות האהובות על מארק ויינס לסירת אטריות (Boat Noodles) — מנות זעירות אך עזות בטעם, נחל של מנות אחת אחרי השנייה. עממי, אותנטי.",
        "location": "Victory Monument area, Ratchathewi, Bangkok, Thailand",
        "lat": 13.7656, "lng": 100.5384,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Mark Wiens Bangkok Guide",
        "recommendationSourceUrl": "https://migrationology.com/travel-guides/bangkok-thailand/",
        "priceLevel": "$", "cuisine": "Thai Boat Noodles",
        "vibe": "No-frills street food",
        "bestTime": "Lunch",
        "googleRating": 4.4, "reviewCount": 1800,
        "tags": ["Mark Wiens", "Boat Noodles", "Street Food", "Cheap Eats"],
    },
    {
        "name": "Soei",
        "description": "השופהאוס האהוב על מארק ויינס במשך שנים — אוכל תאי חריף, נועז ועתיר טעמים. שכונתי, קטן, מקומי.",
        "location": "Bang Sue, Bangkok 10800, Thailand",
        "lat": 13.8050, "lng": 100.5340,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Mark Wiens Bangkok Guide",
        "recommendationSourceUrl": "https://www.eatingthaifood.com/author/admin/",
        "priceLevel": "$$", "cuisine": "Thai (Spicy)",
        "vibe": "Old shophouse, no-frills",
        "bestTime": "Dinner",
        "googleRating": 4.5, "reviewCount": 900,
        "tags": ["Mark Wiens", "Spicy Thai", "Local Favorite"],
    },
    {
        "name": "Mit Ko Yuan",
        "description": "שופהאוס ותיק ליד דמוקרסי מונומנט — אטריות מוקפצות מסורתיות וטום-יום-גונג נדיר. אחד המקומות שמארק ויינס חוזר אליו.",
        "location": "Tanao Rd, Phra Nakhon, Bangkok 10200, Thailand",
        "lat": 13.7561, "lng": 100.5012,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Mark Wiens Bangkok Guide",
        "recommendationSourceUrl": "https://www.eatingthaifood.com/author/admin/",
        "priceLevel": "$$", "cuisine": "Thai (Traditional)",
        "vibe": "Old shophouse, locals' favorite",
        "bestTime": "Dinner",
        "googleRating": 4.4, "reviewCount": 1100,
        "tags": ["Mark Wiens", "Tom Yum Goong", "Old Town"],
    },
    {
        "name": "Jeh O Chula",
        "description": "אגדה של תום-יום אינסטנט (Tom Yum Mama) — תור של שעה+ הוא הנורמה. מוזכרת בכל מדריך מקומי ובסרטוני TikTok. רק בלילה.",
        "location": "113 Soi Charat Mueang, Rong Mueang, Pathum Wan, Bangkok 10330, Thailand",
        "lat": 13.7407, "lng": 100.5253,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "The Ranting Panda — Bangkok Local Eats 2025",
        "recommendationSourceUrl": "https://therantingpanda.com/2025/08/27/panda-picks-best-bangkok-local-food-eateries-to-try-from-jeh-o-chulas-tom-yum-mama-to-thong-smiths-thai-boat-noodles/",
        "priceLevel": "$$", "cuisine": "Thai (Tom Yum Mama)",
        "vibe": "Night-only, long queue, cult favorite",
        "bestTime": "Late night",
        "googleRating": 4.5, "reviewCount": 8500,
        "tags": ["Cult Favorite", "Tom Yum", "Late Night", "Long Queue"],
    },
    {
        "name": "Thong Smith",
        "description": "Boat Noodles בגרסה מודרנית — שילוב של אטריות סירה עם בשרים פרימיום (Wagyu, Kurobuta). פותחה לשרשרת רשמית, איכותית מאוד.",
        "location": "EmQuartier 4th floor, Sukhumvit 35, Khlong Tan Nuea, Watthana, Bangkok 10110, Thailand",
        "lat": 13.7305, "lng": 100.5697,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "The Ranting Panda — Bangkok Local Eats 2025",
        "recommendationSourceUrl": "https://therantingpanda.com/2025/08/27/panda-picks-best-bangkok-local-food-eateries-to-try-from-jeh-o-chulas-tom-yum-mama-to-thong-smiths-thai-boat-noodles/",
        "priceLevel": "$$", "cuisine": "Thai Boat Noodles (Premium)",
        "vibe": "Mall food court but premium",
        "bestTime": "Lunch / Dinner",
        "googleRating": 4.5, "reviewCount": 1400,
        "tags": ["Boat Noodles", "Premium", "EmQuartier", "Wagyu"],
    },
    # --- Wongnai Users' Choice Awards ---
    {
        "name": "Osha Thai Restaurant & Bar",
        "description": "Wongnai Users' Choice — מסעדת תאי האהובה ביותר על המקומיים. מטבח תאי קלאסי באווירה מודרנית ויפה.",
        "location": "99 Witthayu Rd, Lumphini, Pathum Wan, Bangkok 10330, Thailand",
        "lat": 13.7409, "lng": 100.5440,
        "categoryTitle": "תאילנדי",
        "recommendationSource": "Wongnai Users' Choice — Best Thai",
        "recommendationSourceUrl": "https://coconuts.co/bangkok/food-drink/best-restaurants-voted-thais-announced-wongnais-users-choice-awards/",
        "priceLevel": "$$$", "cuisine": "Thai",
        "vibe": "Stylish modern Thai",
        "bestTime": "Dinner",
        "googleRating": 4.4, "reviewCount": 2200,
        "tags": ["Wongnai Choice", "Stylish Thai", "Lumpini"],
    },
    {
        "name": "Jok Toh Diew",
        "description": "ג'וק (דייסת אורז) צ'יינה-טאון אגדית — בעבר היה רק שולחן אחד במקום. Wongnai בחר אותה לטובת הסיני 2024.",
        "location": "Chinatown, Samphanthawong, Bangkok, Thailand",
        "lat": 13.7401, "lng": 100.5108,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Wongnai Users' Choice — Best Chinese",
        "recommendationSourceUrl": "https://coconuts.co/bangkok/food-drink/best-restaurants-voted-thais-announced-wongnais-users-choice-awards/",
        "priceLevel": "$", "cuisine": "Thai-Chinese (Jok)",
        "vibe": "Hole-in-the-wall, single-dish specialist",
        "bestTime": "Breakfast / Lunch",
        "googleRating": 4.3, "reviewCount": 900,
        "tags": ["Wongnai Choice", "Jok", "Chinatown"],
    },
    # --- Editorial / Time Out cafe picks (TRENDING_NOW + SOCIAL_HIDDEN_GEMS) ---
    {
        "name": "965 BKK",
        "description": "פנינה חבויה בטלאט נוי — שופהאוס בן 200 שנה עם פנים וינטג', תערוכות אמנות, וקפה מעולה. ויראלי ב-TikTok 2024-2025.",
        "location": "965 Charoen Krung Rd, Talat Noi, Samphanthawong, Bangkok 10100, Thailand",
        "lat": 13.7318, "lng": 100.5119,
        "categoryTitle": "בתי קפה וקינוחים",
        "recommendationSource": "TikTok / Time Out — Bangkok New Cafes 2025",
        "recommendationSourceUrl": "https://www.timeout.com/bangkok/restaurants/bangkoks-best-new-cafes-of-2025",
        "priceLevel": "$$", "cuisine": "Cafe (Specialty Coffee)",
        "vibe": "200-year shophouse, vintage, creative",
        "bestTime": "Afternoon",
        "googleRating": 4.6, "reviewCount": 700,
        "tags": ["TikTok Viral", "Hidden Gem", "Talat Noi", "Vintage"],
    },
    {
        "name": "Foreste Cafe by Anna Nava",
        "description": "קפה ירוק עוצר נשימה — צמחייה צפופה, אווירה שלווה כמו ביער עירוני. ויראלי ב-TikTok בזכות העיצוב.",
        "location": "Bangkok, Thailand",
        "lat": 13.7330, "lng": 100.5450,
        "categoryTitle": "בתי קפה וקינוחים",
        "recommendationSource": "TikTok viral — @aj.some.more",
        "recommendationSourceUrl": "https://www.tiktok.com/@aj.some.more/video/7421147686377655560",
        "priceLevel": "$$", "cuisine": "Cafe",
        "vibe": "Indoor jungle, photogenic",
        "bestTime": "Afternoon",
        "googleRating": 4.5, "reviewCount": 450,
        "tags": ["TikTok Viral", "Instagrammable", "Green"],
    },
    {
        "name": "Bubble in the Forest Cafe",
        "description": "קפה ביצירת אגדה — בועות זכוכית במים, מזכיר את האיים המלדיביים. אטרקציה אינסטגרמית שצריך לבוא רחוק בשבילה, אבל מאוד שווה לצילומים.",
        "location": "Sam Phran District, Nakhon Pathom (1h from central Bangkok), Thailand",
        "lat": 13.7185, "lng": 100.2110,
        "categoryTitle": "בתי קפה וקינוחים",
        "recommendationSource": "TikTok viral / Klook 15 Insta-cafes",
        "recommendationSourceUrl": "https://www.klook.com/blog/bangkok-cafes-thailand/",
        "priceLevel": "$$", "cuisine": "Cafe",
        "vibe": "Maldives-style bubble pods over water",
        "bestTime": "Day trip",
        "googleRating": 4.3, "reviewCount": 2800,
        "tags": ["TikTok Viral", "Instagrammable", "Day Trip", "Photogenic"],
    },
    {
        "name": "Cafe 747",
        "description": "קפה בתוך בואינג 747 אמיתי — שתי קומות, אפשר לשבת בקוקפיט עם כל הבקרות המקוריות. אטרקציה לחובבי תעופה ומשפחות.",
        "location": "Sam Phran District, Nakhon Pathom (1h from central Bangkok), Thailand",
        "lat": 13.6620, "lng": 100.2470,
        "categoryTitle": "בתי קפה וקינוחים",
        "recommendationSource": "Klook 15 Insta-cafes Bangkok",
        "recommendationSourceUrl": "https://www.klook.com/blog/bangkok-cafes-thailand/",
        "priceLevel": "$$", "cuisine": "Cafe",
        "vibe": "Inside a real Boeing 747, novelty",
        "bestTime": "Day trip",
        "googleRating": 4.4, "reviewCount": 1500,
        "tags": ["Themed Cafe", "Aviation", "Day Trip", "Family"],
    },
    {
        "name": "Capybara Coffee Bangkok",
        "description": "קפה עם קפיברות וחיות מירקאט אמיתיות — אטרקציה משפחתית פופולרית, סניפים בסילום ואקאמאי. ויראלי בקרב משפחות עם ילדים.",
        "location": "Silom and Ekkamai branches, Bangkok, Thailand",
        "lat": 13.7290, "lng": 100.5346,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "Klook 15 Insta-cafes Bangkok",
        "recommendationSourceUrl": "https://www.klook.com/blog/bangkok-cafes-thailand/",
        "priceLevel": "$$", "cuisine": "Cafe / Animal Cafe",
        "vibe": "Family animal cafe, photogenic",
        "bestTime": "Afternoon",
        "googleRating": 4.4, "reviewCount": 600,
        "tags": ["Family", "Animal Cafe", "Capybara", "Instagrammable"],
    },
    {
        "name": "Floral Café (at Napasorn)",
        "description": "קפה בקומה השנייה של חנות פרחים — קינוחים בהשראת פרחים: גלידת ורד, תה לבנדר, עוגות גבינה עם פירות יער. סובב מטונפים בפרחים אמיתיים.",
        "location": "Old Town, Phra Nakhon, Bangkok, Thailand",
        "lat": 13.7530, "lng": 100.4985,
        "categoryTitle": "בתי קפה וקינוחים",
        "recommendationSource": "Klook 15 Insta-cafes Bangkok",
        "recommendationSourceUrl": "https://www.klook.com/blog/bangkok-cafes-thailand/",
        "priceLevel": "$$", "cuisine": "Cafe / Desserts",
        "vibe": "Inside a real flower shop, romantic",
        "bestTime": "Afternoon",
        "googleRating": 4.5, "reviewCount": 1100,
        "tags": ["Instagrammable", "Floral", "Old Town", "Desserts"],
    },
    {
        "name": "B Story Garden Cafe & Restaurant",
        "description": "פנינה חבויה בעיר — גינה ירוקה, חצר פתוחה, אווירה שקטה הרחק מהמולה. אחד הקפה האהובים של בנגקוק ב-2025.",
        "location": "Phra Khanong, Bangkok, Thailand",
        "lat": 13.7148, "lng": 100.5907,
        "categoryTitle": "בתי קפה וקינוחים",
        "recommendationSource": "TikTok viral / Trending 2025",
        "recommendationSourceUrl": "https://www.tiktok.com/discover/best-cafe-in-bangkok-2025",
        "priceLevel": "$$", "cuisine": "Cafe",
        "vibe": "Garden, tranquil",
        "bestTime": "Afternoon",
        "googleRating": 4.4, "reviewCount": 400,
        "tags": ["Garden Cafe", "Hidden Gem", "TikTok Viral"],
    },
    # --- Atlas Obscura curio (SOCIAL_HIDDEN_GEMS) ---
    {
        "name": "Wattana Panich (45-year beef stew)",
        "description": "אגדה אורבנית — סיר אחד של תבשיל בשר שמתבשל ברציפות מעל 45 שנה. רוטב 'מאסטר סטוק' עתיק, חוויה מוזרה וטעימה.",
        "location": "336-338 Ekkamai Rd, Khlong Tan Nuea, Watthana, Bangkok 10110, Thailand",
        "lat": 13.7259, "lng": 100.5854,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Atlas Obscura — Cool & Unusual Bangkok",
        "recommendationSourceUrl": "https://www.atlasobscura.com/things-to-do/bangkok-thailand",
        "priceLevel": "$$", "cuisine": "Chinese (Beef Noodle Soup)",
        "vibe": "Hole-in-the-wall legend, Ekkamai",
        "bestTime": "Lunch",
        "googleRating": 4.3, "reviewCount": 1200,
        "tags": ["Atlas Obscura", "45 Years", "Beef Noodle", "Cult Favorite"],
    },
]


BANGKOK_ATTRACTIONS = [
    # --- TRENDING_NOW — newly opened 2024–2025 ---
    {
        "name": "Dib Bangkok",
        "description": "מוזיאון האמנות העכשווית הבינלאומי הראשון של תאילנד — נפתח דצמבר 2025 במחסן פלדה לשעבר ליד הנמל. אוסף תאילנדי-גלובלי בדיאלוג, מבט-עיניים של עולם האמנות הגלובלי.",
        "location": "Khlong Toei area near the port, Bangkok, Thailand",
        "lat": 13.7080, "lng": 100.5550,
        "categoryTitle": "מוזיאונים ותרבות",
        "recommendationSource": "Monocle — Most Anticipated Museum 2025",
        "recommendationSourceUrl": "https://monocle.com/culture/inside-dib-museum-bangkok/",
        "type": "Contemporary Art Museum", "activity_type": "Culture",
        "duration": "2–3 hours", "price": "Free / TBD",
        "best_time_to_visit": "Afternoon",
        "rating": 4.6, "reviewCount": 200,
        "tags": ["New Dec 2025", "Contemporary Art", "Monocle", "Must-See"],
    },
    {
        "name": "One Bangkok",
        "description": "קומפלקס שימוש מעורב ענק שנפתח אוקטובר 2024 ליד לומפיני — בלוקים נושאיים (The STOREYS, Parade), Mitsukoshi Depachika (קומה ראשונה של אוכל יפני בתאילנד). יעד עירוני חדש.",
        "location": "Wireless Rd, Lumphini, Pathum Wan, Bangkok, Thailand",
        "lat": 13.7320, "lng": 100.5453,
        "categoryTitle": "קניות ושווקים",
        "recommendationSource": "Time Out Bangkok / Trip.com — New 2024",
        "recommendationSourceUrl": "https://my.trip.com/blog/new-attractions-bangkok/?locale=en_my",
        "type": "Mixed-Use Complex", "activity_type": "Shopping / Food",
        "duration": "2–4 hours", "price": "Free entry",
        "best_time_to_visit": "Late afternoon to evening",
        "rating": 4.5, "reviewCount": 1500,
        "tags": ["New Oct 2024", "Shopping", "Mitsukoshi Depachika", "Lumpini"],
    },
    {
        "name": "Space & Time Cube+",
        "description": "אטרקציית סוחפת חדשה (ינואר 2025) — 27 חדרים בנושאים שונים עם הקרנות 720°, הולוגרמות, ומופעי אור אינטראקטיביים. אזור Bang Khae, אטרקציה משפחתית/Instagrammable.",
        "location": "Bang Khae, Bangkok, Thailand",
        "lat": 13.6967, "lng": 100.4030,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "Nation Thailand — Modern 3D Metaverse Museum",
        "recommendationSourceUrl": "https://www.nationthailand.com/life/art-culture/40045410",
        "type": "Immersive Experience", "activity_type": "Entertainment",
        "duration": "1.5–2 hours", "price": "800 THB",
        "costNumeric": 800,
        "best_time_to_visit": "Afternoon / Evening",
        "rating": 4.4, "reviewCount": 300,
        "tags": ["New Jan 2025", "Immersive", "TikTok Viral", "Family"],
    },
    {
        "name": "Jurassic World: The Experience – Bangkok",
        "description": "פארק יורסיק וורלד הגדול בעולם — סצנות אינטראקטיביות בהשראת הסרטים, חוויה 60-90 דקות באנגלית או תאית. פתח באוגוסט 2025.",
        "location": "Megabangna, Samut Prakan (south Bangkok), Thailand",
        "lat": 13.6480, "lng": 100.6840,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "The Smart Local — 15 New Things 2026",
        "recommendationSourceUrl": "https://thesmartlocal.com/read/new-things-to-do-bangkok/",
        "type": "Theme Experience", "activity_type": "Entertainment",
        "duration": "1.5 hours", "price": "1,200 THB",
        "costNumeric": 1200,
        "best_time_to_visit": "Day visit",
        "rating": 4.5, "reviewCount": 250,
        "tags": ["New Aug 2025", "Jurassic World", "Family", "World's Largest"],
    },
    {
        "name": "Bangkok Reflection (One City Center)",
        "description": "מצפה מראות 2 קומות שנפתח ספטמבר 2025 ב-One City Center, רחוב Wireless — נוף פנורמי 360° לעיר ביום, תצוגה צבעונית בלילה. אטרקציית צילום חדשה.",
        "location": "One City Center, Ploenchit Rd, Pathum Wan, Bangkok, Thailand",
        "lat": 13.7430, "lng": 100.5454,
        "categoryTitle": "אתרי חובה",
        "recommendationSource": "KNYCX Journeying — Bangkok New Hot Spots 2026",
        "recommendationSourceUrl": "https://knycxjourneying.com/bangkok-new-attractions-guide/",
        "type": "Observation Deck", "activity_type": "Sightseeing",
        "duration": "1 hour", "price": "350 THB",
        "costNumeric": 350,
        "best_time_to_visit": "Sunset",
        "rating": 4.4, "reviewCount": 150,
        "tags": ["New Sep 2025", "Mirror Observatory", "Instagrammable", "360° View"],
    },
    {
        "name": "Dusit Central Park",
        "description": "אורבן פארק קומפקטי שנפתח ספטמבר 2025 בצומת BTS/MRT של סילום — נקודת מפגש ירוקה, נוחה ונגישה במרכז העיר.",
        "location": "Silom area (Sala Daeng BTS/MRT), Bangkok, Thailand",
        "lat": 13.7282, "lng": 100.5340,
        "categoryTitle": "טבע ונופים",
        "recommendationSource": "Time Out Bangkok — 2025",
        "recommendationSourceUrl": "https://www.timeout.com/bangkok/things-to-do",
        "type": "Urban Park", "activity_type": "Outdoor",
        "duration": "1 hour", "price": "Free",
        "costNumeric": 0,
        "best_time_to_visit": "Morning / Late afternoon",
        "rating": 4.5, "reviewCount": 100,
        "tags": ["New Sep 2025", "Urban Park", "Free", "Silom"],
    },
    # --- INTL_AUTHORITATIVE / EDITORIAL ---
    {
        "name": "Mahanakhon SkyWalk",
        "description": "מצפה הצופה הגבוה ביותר בתאילנד — 314 מטרים, נוף 360° של בנגקוק. רצפת זכוכית בקצה — לא לחלשי לב. אחת התצפיות הכי טובות בעיר.",
        "location": "King Power Mahanakhon, 114 Narathiwat Rd, Silom, Bang Rak, Bangkok 10500, Thailand",
        "lat": 13.7237, "lng": 100.5286,
        "categoryTitle": "אתרי חובה",
        "recommendationSource": "Time Out Bangkok — Best Things to Do",
        "recommendationSourceUrl": "https://www.timeout.com/bangkok/things-to-do/best-things-to-do-in-bangkok",
        "type": "Observation Deck", "activity_type": "Sightseeing",
        "duration": "1.5 hours", "price": "880 THB",
        "costNumeric": 880,
        "best_time_to_visit": "Sunset",
        "rating": 4.6, "reviewCount": 35000,
        "tags": ["Time Out", "Tallest Observation", "Glass Floor", "Sunset"],
    },
    {
        "name": "Song Wat Neighborhood",
        "description": "השכונה שנבחרה ע\"י Time Out לאחת הכי קוּלִיוֹת בעולם 2025 — שופהאוסים מורשתיים, קפה גל שלישי, מסעדות ותיקות וחנויות קטנות בבתי מורשת על הנהר.",
        "location": "Song Wat Rd, Samphanthawong, Bangkok, Thailand",
        "lat": 13.7374, "lng": 100.5102,
        "categoryTitle": "פינות נסתרות",
        "recommendationSource": "Time Out — Coolest Neighborhoods 2025",
        "recommendationSourceUrl": "https://www.nationthailand.com/thailand/bangkok/40047372",
        "type": "Heritage Neighborhood", "activity_type": "Walking",
        "duration": "3–4 hours", "price": "Free",
        "costNumeric": 0,
        "best_time_to_visit": "Morning / Late afternoon",
        "rating": 4.5, "reviewCount": 1200,
        "tags": ["Time Out 2025", "Coolest Neighborhood", "Heritage", "Walk"],
    },
    # --- SOCIAL_HIDDEN_GEMS — Atlas Obscura ---
    {
        "name": "Wat Pariwat (David Beckham Temple)",
        "description": "מקדש בודהיסטי עם פסלי תרבות פופ — דייוויד בקהאם, פיקאצ'ו, טינטין, סופרמן ועוד — חבויים בקירות. חינם, חבוי, מאוד אינסטגרמי. שכונת יאנאווה.",
        "location": "734 Rama III Rd, Bang Phongphang, Yan Nawa, Bangkok 10120, Thailand",
        "lat": 13.6964, "lng": 100.5311,
        "categoryTitle": "פינות נסתרות",
        "recommendationSource": "Atlas Obscura — Cool & Unusual Bangkok",
        "recommendationSourceUrl": "https://www.atlasobscura.com/things-to-do/bangkok-thailand",
        "type": "Buddhist Temple (Pop Culture)", "activity_type": "Culture",
        "duration": "1 hour", "price": "Free",
        "costNumeric": 0,
        "best_time_to_visit": "Morning",
        "rating": 4.5, "reviewCount": 800,
        "tags": ["Atlas Obscura", "Hidden Gem", "Pop Culture", "Free"],
    },
    {
        "name": "Siriraj Medical Museum (Forensic Museum)",
        "description": "אוצר של פתולוגיה, רפואה משפטית, פרזיטולוגיה ואנטומיה — לא למחשמלי לב. אחד המוזיאונים הכי יוצאי דופן בעולם, באוניברסיטת מאהידול.",
        "location": "Siriraj Hospital, Bangkok Noi, Bangkok 10700, Thailand",
        "lat": 13.7588, "lng": 100.4847,
        "categoryTitle": "מוזיאונים ותרבות",
        "recommendationSource": "Atlas Obscura — Cool & Unusual Bangkok",
        "recommendationSourceUrl": "https://www.atlasobscura.com/things-to-do/bangkok-thailand",
        "type": "Medical Museum", "activity_type": "Culture (Unusual)",
        "duration": "1.5 hours", "price": "200 THB",
        "costNumeric": 200,
        "best_time_to_visit": "Morning",
        "rating": 4.2, "reviewCount": 2500,
        "tags": ["Atlas Obscura", "Unusual", "Forensic", "Not for the Squeamish"],
    },
    {
        "name": "Wat Saman Rattanaram (Pink Ganesha)",
        "description": "מקדש פגנש הוורוד הענק — פסל של גנש בורוד בגובה 16 מטרים, אחד מהפסלים הכי מפורסמים ב-IG בעולם הבודהיסטי. שעה דרומית לבנגקוק.",
        "location": "Bang Kaeo, Mueang Chachoengsao, Chachoengsao (1.5h east of Bangkok), Thailand",
        "lat": 13.7000, "lng": 101.0670,
        "categoryTitle": "פינות נסתרות",
        "recommendationSource": "Atlas Obscura / Local guides",
        "recommendationSourceUrl": "https://www.atlasobscura.com/things-to-do/thailand",
        "type": "Buddhist/Hindu Temple", "activity_type": "Culture",
        "duration": "Half day (incl. travel)", "price": "Free",
        "costNumeric": 0,
        "best_time_to_visit": "Day trip",
        "rating": 4.5, "reviewCount": 3000,
        "tags": ["Atlas Obscura", "Pink Ganesha", "Instagrammable", "Day Trip"],
    },
    {
        "name": "Snake Farm (Queen Saovabha Memorial Institute)",
        "description": "חממת נחשים בלב סילום — הדגמות חילוץ ארס יומיות, חינוך על נחשים רעילים של תאילנד. גם משפחתי וגם מוזיאוני, חוויה מקצועית.",
        "location": "1871 Henri Dunant Rd, Pathum Wan, Bangkok 10330, Thailand",
        "lat": 13.7331, "lng": 100.5364,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "Atlas Obscura / TripAdvisor Travelers' Choice",
        "recommendationSourceUrl": "https://www.atlasobscura.com/things-to-do/bangkok-thailand",
        "type": "Snake Farm / Research Institute", "activity_type": "Education",
        "duration": "1.5 hours", "price": "200 THB",
        "costNumeric": 200,
        "best_time_to_visit": "10:30 or 14:30 (extraction demos)",
        "rating": 4.3, "reviewCount": 1800,
        "tags": ["Atlas Obscura", "Family", "Snake Demos", "Educational"],
    },
    # --- LOCAL_RANKINGS / Tourism Authority of Thailand ---
    {
        "name": "Ratchanaddaram Temple (Loha Prasat)",
        "description": "מקדש המתכת — מבנה מרהיב של 37 צריחי ברזל המייצגים את 37 תכונות ההארה. פחות מוכר מ-Wat Pho/Arun אבל לא פחות מרשים, חינם.",
        "location": "2 Maha Chai Rd, Phra Nakhon, Bangkok 10200, Thailand",
        "lat": 13.7544, "lng": 100.5036,
        "categoryTitle": "היסטוריה ודת",
        "recommendationSource": "TAT (Tourism Authority of Thailand)",
        "recommendationSourceUrl": "https://www.tourismthailand.org",
        "type": "Buddhist Temple", "activity_type": "Culture",
        "duration": "1 hour", "price": "Free",
        "costNumeric": 0,
        "best_time_to_visit": "Morning",
        "rating": 4.5, "reviewCount": 3500,
        "tags": ["TAT Featured", "Metal Castle", "Free", "Hidden Gem"],
    },
    # --- FAMILY_FRIENDLY ---
    {
        "name": "KidZania Bangkok",
        "description": "פארק תפקידים לילדים בסיאם פרגון — ילדים מתנסים ב-100+ מקצועות (כבאי, רופא, טייס) בעיר מיניאטורית. מתאים גילאים 4-12.",
        "location": "Siam Paragon 5th floor, Pathum Wan, Bangkok 10330, Thailand",
        "lat": 13.7460, "lng": 100.5347,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "Klook / Family travel guides",
        "recommendationSourceUrl": "https://www.klook.com/",
        "type": "Edutainment", "activity_type": "Entertainment",
        "duration": "4–6 hours", "price": "1,200 THB child / 600 THB adult",
        "costNumeric": 1200,
        "best_time_to_visit": "Morning or full day",
        "rating": 4.6, "reviewCount": 4500,
        "tags": ["Family", "Kids 4-12", "Edutainment", "Siam Paragon"],
    },
    # --- TRENDING_NOW more ---
    {
        "name": "Iconsiam",
        "description": "מתחם נהר ענק עם SookSiam (שוק יוקרתי של אוכל מסורתי מ-77 פרובינציות), חנויות בינלאומיות ובידור. סינטרה לתיירים, גם משפחתי וגם רומנטי.",
        "location": "299 Charoen Nakhon Rd, Khlong San, Bangkok 10600, Thailand",
        "lat": 13.7263, "lng": 100.5095,
        "categoryTitle": "קניות ושווקים",
        "recommendationSource": "Lonely Planet Thailand / TripAdvisor",
        "recommendationSourceUrl": "https://www.lonelyplanet.com/thailand/bangkok",
        "type": "Shopping & Cultural Complex", "activity_type": "Shopping",
        "duration": "3–4 hours", "price": "Free entry",
        "costNumeric": 0,
        "best_time_to_visit": "Late afternoon to evening",
        "rating": 4.6, "reviewCount": 95000,
        "tags": ["Riverside", "SookSiam", "Shopping", "Family"],
    },
]


PATTAYA_RESTAURANTS = [
    {
        "name": "Mum Aroi (Na Kluea)",
        "description": "מסעדת ים פטאיינית אגדית — בלב אזור הדייגים, המחירים הוגנים והדגים נטויים אמיתי. הלהקה מנגנת חי כל לילה מ-20:00. מקומיים ותיירים יחד.",
        "location": "83/4 Soi Na Kluea 4, Na Kluea, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9620, "lng": 100.8841,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "TripAdvisor Travelers' Choice / Travelinsighter 2025",
        "recommendationSourceUrl": "https://travelinsighter.com/best-restaurants-in-pattaya/",
        "priceLevel": "$$", "cuisine": "Thai Seafood",
        "vibe": "Open-air seafood, live band",
        "bestTime": "Dinner",
        "googleRating": 4.4, "reviewCount": 6800,
        "tags": ["TripAdvisor Choice", "Seafood", "Live Music", "Local Favorite"],
    },
    {
        "name": "L'Aroma Pattaya",
        "description": "מסעדה איטלקית-מדיטרנית על שפת חוף ג'ומטיין — אווירה שלווה, נוף ים, מטבח אירופי איכותי. אופציה רומנטית בולטת.",
        "location": "Jomtien Beach Rd, Nong Prue, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.8970, "lng": 100.8810,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "Travelinsighter — Best Restaurants Pattaya 2025",
        "recommendationSourceUrl": "https://travelinsighter.com/best-restaurants-in-pattaya/",
        "priceLevel": "$$$", "cuisine": "Italian / Mediterranean",
        "vibe": "Beachfront, romantic, European",
        "bestTime": "Sunset / Dinner",
        "googleRating": 4.5, "reviewCount": 850,
        "tags": ["Beachfront", "Italian", "Romantic", "Jomtien"],
    },
    {
        "name": "Indian By Nature",
        "description": "מסעדה הודית מובילה בפטאיה — בשרים בתנדור, בריאני, באטר צ'יקן. שירות מדויק, חוויה עליונה לאוהבי תבלינים.",
        "location": "Soi Buakhao, Nong Prue, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9322, "lng": 100.8867,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Travelinsighter / TripAdvisor",
        "recommendationSourceUrl": "https://travelinsighter.com/best-restaurants-in-pattaya/",
        "priceLevel": "$$", "cuisine": "Indian",
        "vibe": "Upscale Indian, attentive service",
        "bestTime": "Dinner",
        "googleRating": 4.6, "reviewCount": 2100,
        "tags": ["Indian", "Tandoor", "Biryani", "Pattaya Top"],
    },
    {
        "name": "Royal Broil Room & Wine Cellar",
        "description": "סטייקאוס יוקרתי במלון Royal Cliff Beach — אווירה אינטימית, סטייקים פרימיום ויינות מובחרים. אופציה רומנטית עליונה לארוחת ערב.",
        "location": "Royal Cliff Beach Hotel, 353 Phra Tamnak Rd, Nong Prue, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9197, "lng": 100.8627,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "Travelinsighter — Top 10 Pattaya 2025",
        "recommendationSourceUrl": "https://travelinsighter.com/best-restaurants-in-pattaya/",
        "priceLevel": "$$$$", "cuisine": "Steakhouse",
        "vibe": "Dimly-lit, refined, hotel",
        "bestTime": "Dinner", "reservationRequired": True,
        "googleRating": 4.6, "reviewCount": 450,
        "tags": ["Royal Cliff", "Steakhouse", "Wine Cellar", "Romantic"],
    },
    {
        "name": "Edge (Hilton Pattaya)",
        "description": "מסעדה אקלקטית בקומה ה-14 של הילטון פטאיה — בופה בינלאומית מהשורה הראשונה, מנות מ-12 מטבחים פתוחים. חזית הים והקניון.",
        "location": "333/101 Moo 9, Beach Rd, Hilton Pattaya, Nong Prue, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9301, "lng": 100.8821,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "Hilton Pattaya / Top 25 Restaurants",
        "recommendationSourceUrl": "https://www.top25restaurants.com/thailand/pattaya/",
        "priceLevel": "$$$", "cuisine": "International Buffet",
        "vibe": "Sea-view buffet, sleek",
        "bestTime": "Lunch / Dinner",
        "googleRating": 4.4, "reviewCount": 2200,
        "tags": ["Hilton", "Buffet", "Sea View", "Family"],
    },
    {
        "name": "The Glasshouse (Silver Beach)",
        "description": "מסעדת ים-תיכון על המים ב-Silver Beach (Na Jomtien) — תפריט תאי+מערבי, סאנסט בלי תחרות. אווירת חופש מלאה.",
        "location": "Silver Beach, Na Jomtien, Bang Lamung, Chonburi 20250, Thailand",
        "lat": 12.8523, "lng": 100.9097,
        "categoryTitle": "חיי לילה ואווירה",
        "recommendationSource": "TAGTHAi Pattaya Bay Guide",
        "recommendationSourceUrl": "https://www.tagthai.com/explore/p/pattaya-bay-restaurant-guide",
        "priceLevel": "$$$", "cuisine": "Thai-Western Seafood",
        "vibe": "Beachfront, sunset, breezy",
        "bestTime": "Sunset",
        "googleRating": 4.5, "reviewCount": 980,
        "tags": ["Beachfront", "Sunset", "Silver Beach"],
    },
    {
        "name": "Jasmin's Café",
        "description": "קפה קז'ואל אהוב על תיירים ומקומיים — ארוחת בוקר/בראנץ' מערבית מעולה וגם תאי אותנטי. מחירים סבירים, כל דבר טעים.",
        "location": "Soi 6/1, Beach Rd, Pattaya, Chonburi 20150, Thailand",
        "lat": 12.9437, "lng": 100.8843,
        "categoryTitle": "בתי קפה וקינוחים",
        "recommendationSource": "Hotels.com / Go Guides",
        "recommendationSourceUrl": "https://www.hotels.com/go/thailand/best-restaurants-pattaya",
        "priceLevel": "$$", "cuisine": "Cafe / Western & Thai",
        "vibe": "Casual breakfast/brunch",
        "bestTime": "Breakfast / Brunch",
        "googleRating": 4.6, "reviewCount": 1400,
        "tags": ["Breakfast", "Brunch", "Casual", "Value"],
    },
    {
        "name": "Mantra Restaurant & Bar",
        "description": "מסעדה אסיאתית-בינלאומית מרכזית בפטאיה — תפריט בופה Sunday Brunch אגדי, אווירה תיאטרלית, חוויה מלאה. מומלץ מ-Top 25.",
        "location": "240 Beach Rd, Pattaya 20150, Thailand",
        "lat": 12.9461, "lng": 100.8853,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "Top 25 Restaurants Pattaya",
        "recommendationSourceUrl": "https://www.top25restaurants.com/thailand/pattaya/",
        "priceLevel": "$$$", "cuisine": "Pan-Asian / International",
        "vibe": "Theatrical, multi-cuisine",
        "bestTime": "Dinner / Sunday Brunch",
        "googleRating": 4.5, "reviewCount": 3200,
        "tags": ["Sunday Brunch", "Pan-Asian", "Beach Rd"],
    },
    {
        "name": "Sketch Restaurant",
        "description": "מסעדת fine dining פטאיינית עכשווית — תפריט יצירתי, מבחר יינות מצוין. חוויית שף שמתחרה בבנגקוק. מוזכרת בכל מדריך מקצועי 2025.",
        "location": "Pratumnak Hill, Nong Prue, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9241, "lng": 100.8634,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "Trip.com Best Pattaya 2026",
        "recommendationSourceUrl": "https://in.trip.com/toplist/tripbest/pattaya-best-must-visit-restaurants-100900014253/",
        "priceLevel": "$$$$", "cuisine": "Modern Thai-Western",
        "vibe": "Chef-driven, intimate",
        "bestTime": "Dinner", "reservationRequired": True,
        "googleRating": 4.7, "reviewCount": 280,
        "tags": ["Fine Dining", "Chef-driven", "Pratumnak"],
    },
    {
        "name": "Mae Sai (Floating Market Pattaya)",
        "description": "מסעדה מקומית בשוק הצף עם דגים על המים — אווירה אותנטית, אטריות תאי, פאד תאי, מאכלים מסורתיים. גם אטרקציה וגם ארוחה.",
        "location": "Pattaya Floating Market, Soi Sukhumvit-Pattaya 32, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9067, "lng": 100.9019,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "TAT / Local guides",
        "recommendationSourceUrl": "https://www.tourismthailand.org",
        "priceLevel": "$", "cuisine": "Thai Street Food",
        "vibe": "Floating market boats",
        "bestTime": "Lunch",
        "googleRating": 4.0, "reviewCount": 3500,
        "tags": ["Floating Market", "Street Food", "Family"],
    },
    {
        "name": "Cabbages & Condoms",
        "description": "מסעדה תאילנדית קלאסית עם רעיון ייחודי — קמפיין מודעות לתכנון משפחה. הקירות מקושטים בקונדומים. אטרקציה+אוכל טוב. רשת אבל הסניף הפטאיני יחיד מסוגו.",
        "location": "366/11 Phra Tamnak Rd, Nong Prue, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9220, "lng": 100.8755,
        "categoryTitle": "פינות נסתרות",
        "recommendationSource": "Atlas Obscura-style novelty / TripAdvisor",
        "recommendationSourceUrl": "https://www.atlasobscura.com/things-to-do/bangkok-thailand",
        "priceLevel": "$$", "cuisine": "Thai",
        "vibe": "Quirky, garden setting, family-planning themed",
        "bestTime": "Dinner",
        "googleRating": 4.3, "reviewCount": 1900,
        "tags": ["Quirky", "Family Planning Cause", "Garden"],
    },
    {
        "name": "Bruno's",
        "description": "מסעדה אירופית שוויצרית/צרפתית בפטאיה — סטייקים, פוקטות, נאמני לקוחות לאורך שנים. רשימת יין מרשימה.",
        "location": "306/63 Thep Prasit 8, Nong Prue, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9145, "lng": 100.8889,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "TripAdvisor / Wanderlog Best 50 Pattaya",
        "recommendationSourceUrl": "https://wanderlog.com/list/geoCategory/74030/where-to-eat-best-restaurants-in-pattaya",
        "priceLevel": "$$$", "cuisine": "European (Swiss/French)",
        "vibe": "Classic European, refined",
        "bestTime": "Dinner",
        "googleRating": 4.7, "reviewCount": 1100,
        "tags": ["European", "Steak", "Wine"],
    },
    {
        "name": "Punjab Grill",
        "description": "סניף של רשת הגריל ההודית המפורסמת — מנות צפון-הודיות יוקרתיות במתחם Central Festival. שירות מצוין, אופציה איכותית באמצע העיר.",
        "location": "Central Pattaya Festival, Beach Rd, Pattaya 20150, Thailand",
        "lat": 12.9320, "lng": 100.8814,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Hungry Hub Best Pattaya",
        "recommendationSourceUrl": "https://web.hungryhub.com/en/restaurants/group/pattaya-best-restaurants-in-pattaya/web",
        "priceLevel": "$$$", "cuisine": "Indian (North Indian)",
        "vibe": "Mall upscale Indian",
        "bestTime": "Dinner",
        "googleRating": 4.4, "reviewCount": 850,
        "tags": ["Indian", "Punjab Grill", "Central Festival"],
    },
    {
        "name": "PIC Kitchen",
        "description": "מסעדה תאילנדית בסגנון בית-מסורתי על נכסים בני 30 שנה — אווירת בית עם מנות תאי קלאסיות. שולחנות במורד הקריפלינג. אופציה משפחתית.",
        "location": "Soi 5, Beach Rd, Pattaya 20150, Thailand",
        "lat": 12.9461, "lng": 100.8826,
        "categoryTitle": "מסעדות משפחתיות",
        "recommendationSource": "Hungry Hub / TripAdvisor",
        "recommendationSourceUrl": "https://web.hungryhub.com/en/restaurants/group/pattaya-best-restaurants-in-pattaya/web",
        "priceLevel": "$$", "cuisine": "Thai (Traditional)",
        "vibe": "Traditional Thai house, garden seating",
        "bestTime": "Dinner",
        "googleRating": 4.5, "reviewCount": 2400,
        "tags": ["Traditional Thai", "Family", "Garden"],
    },
    {
        "name": "Casa Pascal",
        "description": "מסעדת fine dining שוויצרית-אירופית בלב פטאיה — מנגרינים מטוגנים, פונדו וסטייקים. אופציה אסטוויה ל-romantic dinner.",
        "location": "485/4 Soi Maliwan, Beach Rd, Pattaya 20150, Thailand",
        "lat": 12.9277, "lng": 100.8814,
        "categoryTitle": "יוקרה ומישלן",
        "recommendationSource": "TripAdvisor / Pattaya Mail",
        "recommendationSourceUrl": "https://www.tripadvisor.com/Restaurants-g293919-Pattaya_Chonburi_Province.html",
        "priceLevel": "$$$$", "cuisine": "European (Swiss/French)",
        "vibe": "Refined European, romantic",
        "bestTime": "Dinner", "reservationRequired": True,
        "googleRating": 4.7, "reviewCount": 950,
        "tags": ["Fine Dining", "European", "Romantic"],
    },
    {
        "name": "Moom Aroi (The Original)",
        "description": "סניף האם של מום-ארואי — נוף ים נעים, דגים טריים נטויים מקריפלינג קטן. מקום מקומי קלאסי לחובבי דגים.",
        "location": "201/24 Soi Wong Amat 12, Na Kluea, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9628, "lng": 100.8839,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "TripAdvisor Top Seafood",
        "recommendationSourceUrl": "https://www.tripadvisor.com/Restaurants-g293919-c33-Pattaya_Chonburi_Province.html",
        "priceLevel": "$$", "cuisine": "Thai Seafood",
        "vibe": "Local seaside seafood, casual",
        "bestTime": "Lunch / Dinner",
        "googleRating": 4.3, "reviewCount": 4800,
        "tags": ["Seafood", "Na Kluea", "Local"],
    },
    {
        "name": "Rim Talay Seafood",
        "description": "מסעדה תאי-סינית גדולה על שפת הים — מאכלי ים גדולים למשפחות, פופולרית בקרב הקבוצות. גם תיירים גם מקומיים.",
        "location": "Na Jomtien Beach Rd, Bang Lamung, Chonburi 20250, Thailand",
        "lat": 12.8615, "lng": 100.9098,
        "categoryTitle": "מסעדות משפחתיות",
        "recommendationSource": "Local Pattaya guides / TripAdvisor",
        "recommendationSourceUrl": "https://www.tripadvisor.com/Restaurants-g293919-Pattaya_Chonburi_Province.html",
        "priceLevel": "$$", "cuisine": "Thai-Chinese Seafood",
        "vibe": "Large family seafood, sea views",
        "bestTime": "Dinner",
        "googleRating": 4.2, "reviewCount": 1800,
        "tags": ["Seafood", "Family", "Na Jomtien"],
    },
    {
        "name": "Leng Kee (24-hour Chinese)",
        "description": "מסעדה סינית 24/7 — מנות סיניות-תאי קלאסיות 24 שעות. תחנת הצלה אחרי לילה ארוך, אופציה תקציבית טובה.",
        "location": "Pattaya South Rd, Pattaya 20150, Thailand",
        "lat": 12.9301, "lng": 100.8845,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Local guides / TripAdvisor",
        "recommendationSourceUrl": "https://www.tripadvisor.com/Restaurants-g293919-Pattaya_Chonburi_Province.html",
        "priceLevel": "$", "cuisine": "Thai-Chinese",
        "vibe": "24-hour, no-frills",
        "bestTime": "Late night / Anytime",
        "googleRating": 4.0, "reviewCount": 2300,
        "tags": ["24 Hour", "Chinese", "Budget"],
    },
]


PATTAYA_ATTRACTIONS = [
    # --- Atlas Obscura hidden gems ---
    {
        "name": "The Bottle Art Museum",
        "description": "מוזיאון אמנות בבקבוקים — אוסף מפורט של מיניאטורות יד בתוך בקבוקים, מעבודה של אמן הולנדי. אטרקציה זעירה אבל מרשימה, Atlas Obscura.",
        "location": "Pattaya 2nd Rd, Pattaya 20150, Thailand",
        "lat": 12.9485, "lng": 100.8839,
        "categoryTitle": "מוזיאונים ותרבות",
        "recommendationSource": "Atlas Obscura — Cool & Unusual Pattaya",
        "recommendationSourceUrl": "https://www.atlasobscura.com/things-to-do/pattaya-thailand",
        "type": "Art Museum", "activity_type": "Culture",
        "duration": "45 mins", "price": "150 THB",
        "costNumeric": 150,
        "best_time_to_visit": "Afternoon",
        "rating": 4.3, "reviewCount": 280,
        "tags": ["Atlas Obscura", "Quirky", "Bottle Art"],
    },
    {
        "name": "Nong Nooch Dinosaur Valley",
        "description": "עמק עם 180+ דגמי דינוזאורים בגודל אמיתי — שילוב של גן ופארק שעשועים בתוך גני נונג נוך. חוויה מ-stress-נופלת מטעם משפחות.",
        "location": "Inside Nong Nooch Tropical Garden, 34/1 Sukhumvit Rd, Najomtien, Sattahip, Chonburi 20250, Thailand",
        "lat": 12.7639, "lng": 100.9333,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "Atlas Obscura / Family travel",
        "recommendationSourceUrl": "https://www.atlasobscura.com/things-to-do/pattaya-thailand",
        "type": "Dinosaur Park", "activity_type": "Entertainment",
        "duration": "2 hours", "price": "Included with Nong Nooch entry",
        "best_time_to_visit": "Morning",
        "rating": 4.4, "reviewCount": 3500,
        "tags": ["Dinosaurs", "Family", "Nong Nooch", "180+ models"],
    },
    {
        "name": "Hat Nang Ram (Dancing Girl Beach)",
        "description": "חוף חבוי 20 ק\"מ דרומית לפטאיה — נקי, רגוע ופחות צפוף. שייט שקט מהמולה של פטאיה. בקצה הצפוני של בסיס הצי.",
        "location": "Sattahip District, Chonburi (20km south of Pattaya), Thailand",
        "lat": 12.6754, "lng": 100.9123,
        "categoryTitle": "חופים ומים",
        "recommendationSource": "Thrillark / Sillysuitcase Hidden Gems",
        "recommendationSourceUrl": "https://www.thrillark.com/blog/hidden-gems-pattaya/",
        "type": "Hidden Beach", "activity_type": "Beach",
        "duration": "Half day", "price": "Free",
        "costNumeric": 0,
        "best_time_to_visit": "Weekday morning",
        "rating": 4.4, "reviewCount": 750,
        "tags": ["Hidden Beach", "Quiet", "Sattahip", "Hat Nang Ram"],
    },
    {
        "name": "Pattaya Viewpoint (Pratumnak Hill)",
        "description": "תצפית הקלאסית של פטאיה על גבעת פראטומנק — נוף קשתי של מפרץ פטאיה. שעת השקיעה (18:30) מאגית. כתובת הסלפי הקלאסית.",
        "location": "Pratumnak Hill, Nong Prue, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9180, "lng": 100.8689,
        "categoryTitle": "אתרי חובה",
        "recommendationSource": "Healthland Spa / Top 20 Pattaya",
        "recommendationSourceUrl": "https://www.healthlandspa.com/en/journal/best-20-tourist-attractions-in-pattaya",
        "type": "Viewpoint", "activity_type": "Sightseeing",
        "duration": "30 mins", "price": "Free",
        "costNumeric": 0,
        "best_time_to_visit": "Sunset (18:30)",
        "rating": 4.4, "reviewCount": 28000,
        "tags": ["Viewpoint", "Sunset", "Free", "Pratumnak"],
    },
    # --- Family-friendly / Newly opened ---
    {
        "name": "Harbor Land Pattaya (Asia's largest indoor playground)",
        "description": "מתחם משחק מקורה הגדול באסיה (12,000 מ\"ר) — 11 אזורי משחק, 20 מתקנים, מגלשה הכי גבוהה באסיה. בקניון Harbor Pattaya. מושלם למשפחות עם ילדים.",
        "location": "Harbor Pattaya Mall, Pattaya Klang Rd, Nong Prue, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9321, "lng": 100.8898,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "Family travel guides 2025",
        "recommendationSourceUrl": "https://atmindgroup.com/alterahotelandresidence/pattaya-hotel/family-friendly-pattaya/",
        "type": "Indoor Playground", "activity_type": "Entertainment",
        "duration": "3–5 hours", "price": "650 THB child / 200 THB adult",
        "costNumeric": 650,
        "best_time_to_visit": "Anytime (indoors)",
        "rating": 4.5, "reviewCount": 4200,
        "tags": ["Family", "Asia's Largest", "Indoor", "Kids"],
    },
    {
        "name": "Ripley's Believe It or Not Pattaya",
        "description": "מתחם בידור משפחתי במרכז הקניות Royal Garden — תיאטרון מקרני נע, בתי רפאים, מבוך לייזר, יותר מ-350 חפצים ב-10 גלריות.",
        "location": "Royal Garden Plaza, 218 Beach Rd, Pattaya 20150, Thailand",
        "lat": 12.9381, "lng": 100.8855,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "Klook / Family travel",
        "recommendationSourceUrl": "https://www.klook.com/",
        "type": "Family Entertainment", "activity_type": "Entertainment",
        "duration": "2–3 hours", "price": "800 THB",
        "costNumeric": 800,
        "best_time_to_visit": "Afternoon",
        "rating": 4.2, "reviewCount": 5800,
        "tags": ["Ripley's", "Family", "Haunted House", "Laser Maze"],
    },
    {
        "name": "Khao Kheow Open Zoo",
        "description": "ספארי 2000 דונם עם 8000+ חיות — עגלות גולף בתוך הפארק, אזור Cats Complex עם אריות ונמרים, האכלת ג'ירפות. אופציה משפחתית מעולה ליום.",
        "location": "235 Mu 7, Bang Phra, Si Racha, Chonburi 20210, Thailand",
        "lat": 13.2245, "lng": 100.9358,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "Tourism Authority Thailand / Family guides",
        "recommendationSourceUrl": "https://www.tourismthailand.org",
        "type": "Open Zoo", "activity_type": "Wildlife",
        "duration": "Full day", "price": "300 THB",
        "costNumeric": 300,
        "best_time_to_visit": "Morning",
        "rating": 4.5, "reviewCount": 12000,
        "tags": ["Family", "Open Zoo", "Wildlife", "Full Day"],
    },
    {
        "name": "Elephant Jungle Sanctuary Pattaya",
        "description": "מקלט פילים אתי — האכלה, רחצה ולמידה על שיקום פילים. ללא רכיבה, ללא ניצול. אופציה אתית למשפחות.",
        "location": "Bang Lamung District, Chonburi 20150, Thailand",
        "lat": 12.9710, "lng": 101.0150,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "Elephant Jungle Sanctuary / Ethical tourism",
        "recommendationSourceUrl": "https://elephantjunglesanctuary.com/blog/places-visit-pattaya-with-family/",
        "type": "Elephant Sanctuary", "activity_type": "Wildlife",
        "duration": "Half day", "price": "2,500 THB",
        "costNumeric": 2500,
        "best_time_to_visit": "Morning",
        "rating": 4.7, "reviewCount": 5500,
        "tags": ["Ethical", "Elephants", "Family", "No Riding"],
    },
    {
        "name": "Pattaya Submarine Tour",
        "description": "שייט עם צוללת תיירותית שמרדדת ל-30 מטר מתחת לים — חוויה ייחודית למשפחות, רואים שוניות אלמוגים ודגים טרופיים. חדש יחסית, מומלץ למשפחות עם ילדים שאוהבים מים.",
        "location": "Bali Hai Pier, Pattaya 20150, Thailand",
        "lat": 12.9237, "lng": 100.8757,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "Klook / GetYourGuide",
        "recommendationSourceUrl": "https://www.getyourguide.com/pattaya-l182/family-friendly-activities-tc1094/",
        "type": "Submarine Tour", "activity_type": "Adventure",
        "duration": "2 hours", "price": "2,800 THB",
        "costNumeric": 2800,
        "best_time_to_visit": "Day",
        "rating": 4.4, "reviewCount": 900,
        "tags": ["Submarine", "Family", "Unique"],
    },
    {
        "name": "Million Years Stone Park & Crocodile Farm",
        "description": "פארק אבנים בני מיליון שנים + חוות תנינים — קרובה לפטאיה, מופעי תנינים, אבנים מעוצבות בצורות מוזרות, אזור בעלי חיים. אופציה שונה מהרגיל.",
        "location": "22/1 Moo 1, Nong Pla Lai, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9633, "lng": 100.9745,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "Local Pattaya guides",
        "recommendationSourceUrl": "https://www.tripadvisor.com/Attractions-g293919-Activities-zft11306-Pattaya_Chonburi_Province.html",
        "type": "Themed Park", "activity_type": "Entertainment",
        "duration": "3 hours", "price": "500 THB",
        "costNumeric": 500,
        "best_time_to_visit": "Morning",
        "rating": 4.2, "reviewCount": 2800,
        "tags": ["Family", "Crocodile Show", "Stone Park"],
    },
    {
        "name": "Wong Amat Mangrove Boat Tour",
        "description": "שייט סירה איטית בין מנגרובים בצפון פטאיה — נופים שקטים, ציפורים, סדרת אקולוגית. אטרקצייה אקולוגית פחות מוכרת.",
        "location": "Wong Amat, Na Kluea, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.9710, "lng": 100.8870,
        "categoryTitle": "טבע ונופים",
        "recommendationSource": "Eco-tourism local operators",
        "recommendationSourceUrl": "https://www.healthlandspa.com/en/journal/best-20-tourist-attractions-in-pattaya",
        "type": "Mangrove Boat Tour", "activity_type": "Nature",
        "duration": "1.5 hours", "price": "800 THB",
        "costNumeric": 800,
        "best_time_to_visit": "Morning",
        "rating": 4.4, "reviewCount": 600,
        "tags": ["Nature", "Mangrove", "Quiet"],
    },
    {
        "name": "Pattaya Sky Coaster (Pattaya Park)",
        "description": "סקיי-קוסטר — חוויית התעופה היחידה בפטאיה. תלות אלפי מטר מעל קרקע. נמצא במגדל Pattaya Park, נחיתה רכה. אטרקציה אדרנלינית.",
        "location": "Pattaya Park Beach Resort, 345 Jomtien Beach Rd, Bang Lamung, Chonburi 20150, Thailand",
        "lat": 12.8961, "lng": 100.8807,
        "categoryTitle": "אקסטרים ופעילויות",
        "recommendationSource": "Pattaya Park Tower / Adventure tourism",
        "recommendationSourceUrl": "https://www.tripadvisor.com/Attractions-g293919-Pattaya_Chonburi_Province.html",
        "type": "Sky Coaster", "activity_type": "Adventure",
        "duration": "30 mins", "price": "300 THB",
        "costNumeric": 300,
        "best_time_to_visit": "Sunset",
        "rating": 4.2, "reviewCount": 1500,
        "tags": ["Adrenaline", "Sky Coaster", "Sunset View"],
    },
]


KOHCHANG_RESTAURANTS = [
    {
        "name": "Chow Lay Restaurant",
        "description": "מסעדת ים על המים בלונלי ביץ' — סלים זול עם דגים טריים, מנות תאי קלאסיות. אווירה רגועה, גם מקומיים אוכלים כאן.",
        "location": "Lonely Beach, Ko Chang, Trat 23170, Thailand",
        "lat": 11.9920, "lng": 102.3160,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Explore Koh Chang 24/25 Season",
        "recommendationSourceUrl": "https://explorekohchang.com/koh-chang/restaurants/",
        "priceLevel": "$$", "cuisine": "Thai Seafood",
        "vibe": "Casual seaside, locals + travelers",
        "bestTime": "Dinner",
        "googleRating": 4.4, "reviewCount": 480,
        "tags": ["Lonely Beach", "Seafood", "Local"],
    },
    {
        "name": "Nongyim Seafood",
        "description": "מסעדת דגים בלונלי ביץ' — דייגים מקומיים מספקים את הדגים יום-יום. ירוק, פשוט, אבל הטעמים אמיתיים.",
        "location": "Lonely Beach, Ko Chang, Trat 23170, Thailand",
        "lat": 11.9931, "lng": 102.3140,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Explore Koh Chang Restaurant Guide",
        "recommendationSourceUrl": "https://explorekohchang.com/koh-chang/restaurants/",
        "priceLevel": "$$", "cuisine": "Thai Seafood",
        "vibe": "Local seafood, no-frills",
        "bestTime": "Dinner",
        "googleRating": 4.3, "reviewCount": 350,
        "tags": ["Lonely Beach", "Seafood", "Family"],
    },
    {
        "name": "Cliff Cottage",
        "description": "מסעדת תצפית על מצוק בלונלי ביץ' — נוף שקיעה מרשים, תפריט תאי+בינלאומי. שווה את הטיפוס.",
        "location": "Lonely Beach, Ko Chang, Trat 23170, Thailand",
        "lat": 11.9892, "lng": 102.3128,
        "categoryTitle": "חיי לילה ואווירה",
        "recommendationSource": "I Am Koh Chang Guide",
        "recommendationSourceUrl": "https://iamkohchang.com/restaurants/guide.html",
        "priceLevel": "$$", "cuisine": "Thai-International",
        "vibe": "Cliffside, sunset views",
        "bestTime": "Sunset",
        "googleRating": 4.5, "reviewCount": 620,
        "tags": ["Cliffside", "Sunset", "Lonely Beach"],
    },
    {
        "name": "Friend Seafood",
        "description": "מסעדת ים פופולרית בקאי בא ביץ' — קצה צפוני של החוף, דגים טריים. בעלי בית מוזרים שתמיד נחמדים.",
        "location": "Northern end of Kai Bae Beach, Ko Chang, Trat 23170, Thailand",
        "lat": 12.0432, "lng": 102.2997,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Explore Koh Chang Kai Bae 24/25",
        "recommendationSourceUrl": "https://explorekohchang.com/koh-chang/restaurants/kai-bae-beach/",
        "priceLevel": "$$", "cuisine": "Thai Seafood",
        "vibe": "Friendly local seafood",
        "bestTime": "Lunch / Dinner",
        "googleRating": 4.4, "reviewCount": 560,
        "tags": ["Kai Bae", "Seafood", "Family"],
    },
    {
        "name": "Baan Kai Bae Seafood",
        "description": "מסעדת ים בכניסה הדרומית של קאי בא ביץ' — אווירת בית, מנות גדולות, שירות חמים. אופציה משפחתית.",
        "location": "South end Kai Bae Beach (near bridge), Ko Chang, Trat 23170, Thailand",
        "lat": 12.0349, "lng": 102.3025,
        "categoryTitle": "מסעדות משפחתיות",
        "recommendationSource": "Explore Koh Chang Kai Bae",
        "recommendationSourceUrl": "https://explorekohchang.com/koh-chang/restaurants/kai-bae-beach/",
        "priceLevel": "$$", "cuisine": "Thai Seafood",
        "vibe": "Family-style seaside",
        "bestTime": "Dinner",
        "googleRating": 4.3, "reviewCount": 420,
        "tags": ["Kai Bae", "Seafood", "Family"],
    },
    {
        "name": "Koh Chang Grand Lagoon Restaurant",
        "description": "מסעדת חוף ב-White Sand Beach — שולחנות על החול תחת כוכבים, נרות וכוסות. רומנטית, מוזיקה חיה לפעמים.",
        "location": "White Sand Beach (Hat Sai Khao), Ko Chang, Trat 23170, Thailand",
        "lat": 12.0701, "lng": 102.2929,
        "categoryTitle": "חיי לילה ואווירה",
        "recommendationSource": "Explore Koh Chang White Sand Beach 24/25",
        "recommendationSourceUrl": "https://explorekohchang.com/koh-chang/restaurants/white-sand-beach/",
        "priceLevel": "$$$", "cuisine": "Thai-International",
        "vibe": "Beachfront with candles",
        "bestTime": "Dinner / Sunset",
        "googleRating": 4.4, "reviewCount": 980,
        "tags": ["Beachfront", "Romantic", "White Sand Beach"],
    },
    {
        "name": "Sangtawan",
        "description": "מסעדה+בר בלונלי ביץ' — BBQ ערב על החול, פסטיבל קטן בכל לילה. אווירת תרמילאים אבל אוכל איכותי.",
        "location": "Lonely Beach, Ko Chang, Trat 23170, Thailand",
        "lat": 11.9919, "lng": 102.3164,
        "categoryTitle": "חיי לילה ואווירה",
        "recommendationSource": "Explore Koh Chang Restaurant Guide",
        "recommendationSourceUrl": "https://explorekohchang.com/koh-chang/restaurants/",
        "priceLevel": "$$", "cuisine": "Thai BBQ",
        "vibe": "Beach BBQ, backpacker",
        "bestTime": "Dinner",
        "googleRating": 4.3, "reviewCount": 380,
        "tags": ["BBQ", "Beach", "Lonely Beach"],
    },
    {
        "name": "El Barrio",
        "description": "מסעדה מקסיקנית אותנטית — טאקוס, ברוריטוס וקוקטיילים. הפתעה תרבותית בקוה צ'אנג, פופולרית בקרב מטיילים אמריקאים/אירופים.",
        "location": "Klong Prao Beach area, Ko Chang, Trat 23170, Thailand",
        "lat": 12.0521, "lng": 102.3068,
        "categoryTitle": "פינות נסתרות",
        "recommendationSource": "Explore Koh Chang / Travel Fish",
        "recommendationSourceUrl": "https://www.travelfish.org/eatandmeet/thailand/eastern_thailand/trat/ko_chang/eat",
        "priceLevel": "$$", "cuisine": "Mexican",
        "vibe": "Casual Mexican, cocktails",
        "bestTime": "Dinner",
        "googleRating": 4.6, "reviewCount": 290,
        "tags": ["Mexican", "Cocktails", "Hidden Gem"],
    },
    {
        "name": "Pizzeria Spaghetteria Toscana",
        "description": "פיצריה איטלקית אותנטית בלב קוה צ'אנג — בעלים איטלקיים, פיצה בטאבון אבן, מקרונים תוצרת בית. הפתעה איכותית.",
        "location": "White Sand Beach, Ko Chang, Trat 23170, Thailand",
        "lat": 12.0689, "lng": 102.2939,
        "categoryTitle": "פיצה",
        "recommendationSource": "Explore Koh Chang / Hopsa",
        "recommendationSourceUrl": "https://hopsa.io/en/blog/post/things-to-do,10-best-restaurants-on-koh-chang-a-culinary-tour-of-thailand-island",
        "priceLevel": "$$", "cuisine": "Italian",
        "vibe": "Authentic Italian-run pizzeria",
        "bestTime": "Dinner",
        "googleRating": 4.6, "reviewCount": 720,
        "tags": ["Italian", "Pizza", "Stone Oven"],
    },
    {
        "name": "Toh Pho Restaurant",
        "description": "מסעדה תאית פופולרית ב-Kai Bae — אטריות, פאד תאי, סלטים. מחירים זולים, פורציות גדולות, אוויר חופשי.",
        "location": "Kai Bae Beach, Ko Chang, Trat 23170, Thailand",
        "lat": 12.0398, "lng": 102.3009,
        "categoryTitle": "מסעדות משפחתיות",
        "recommendationSource": "Travel Fish / Local guides",
        "recommendationSourceUrl": "https://www.travelfish.org/eatandmeet/thailand/eastern_thailand/trat/ko_chang/eat",
        "priceLevel": "$", "cuisine": "Thai",
        "vibe": "Casual Thai street-style",
        "bestTime": "Lunch / Dinner",
        "googleRating": 4.3, "reviewCount": 540,
        "tags": ["Budget", "Thai Classics", "Family"],
    },
    {
        "name": "Magic Garden Bar & Restaurant",
        "description": "בר/מסעדה ייחודי בלונלי ביץ' — גינה טרופית, ציורי קיר פסיכדליים, אווירה תרמילאית קלאסית. שני קוקטיילים זה לילה ארוך.",
        "location": "Lonely Beach, Ko Chang, Trat 23170, Thailand",
        "lat": 11.9925, "lng": 102.3155,
        "categoryTitle": "חיי לילה ואווירה",
        "recommendationSource": "I Am Koh Chang / Travel Fish",
        "recommendationSourceUrl": "https://iamkohchang.com/restaurants/guide.html",
        "priceLevel": "$$", "cuisine": "Thai-International / Bar",
        "vibe": "Backpacker garden bar, psychedelic art",
        "bestTime": "Evening",
        "googleRating": 4.5, "reviewCount": 850,
        "tags": ["Backpacker", "Garden Bar", "Lonely Beach"],
    },
    {
        "name": "Salakkok Bay Restaurant",
        "description": "מסעדה כפרית בכפר Salakkok על מצוף הים — מתאימה לטיולי דייגים, סטים של דגים גדולים. דרך מצוינת לחוות את החוף המזרחי השקט.",
        "location": "Salakkok Fishing Village, Ko Chang, Trat 23170, Thailand",
        "lat": 11.9905, "lng": 102.3855,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "TAT / Eco-tourism",
        "recommendationSourceUrl": "https://www.tourismthailand.org",
        "priceLevel": "$$", "cuisine": "Thai Seafood",
        "vibe": "Fishing village, on stilts",
        "bestTime": "Lunch",
        "googleRating": 4.2, "reviewCount": 220,
        "tags": ["Fishing Village", "East Coast", "Authentic"],
    },
    {
        "name": "Dee Cafe & Bakery",
        "description": "קפה+מאפיה מערבית בקאי בא — קרואסונים, סקונים, עוגות, קפה איכותי. מקום מצוין לבוקר רגוע.",
        "location": "Kai Bae Beach, Ko Chang, Trat 23170, Thailand",
        "lat": 12.0405, "lng": 102.3000,
        "categoryTitle": "בתי קפה וקינוחים",
        "recommendationSource": "Travel Fish / Local recs",
        "recommendationSourceUrl": "https://www.travelfish.org/eatandmeet/thailand/eastern_thailand/trat/ko_chang/eat",
        "priceLevel": "$$", "cuisine": "Cafe / Bakery",
        "vibe": "Western bakery, cozy",
        "bestTime": "Breakfast",
        "googleRating": 4.4, "reviewCount": 380,
        "tags": ["Cafe", "Bakery", "Breakfast"],
    },
    {
        "name": "Baan Rim Nam (Tha Mai Rud)",
        "description": "מסעדה על הנהר בבאן באנג באו — בקבוקי בירה קרים ודגים טריים, אווירת כפר דייגים אותנטית. נחשבת לחווייה הקולינרית האותנטית של הכפר.",
        "location": "Bang Bao Village, Ko Chang, Trat 23170, Thailand",
        "lat": 11.9706, "lng": 102.3475,
        "categoryTitle": "אוכל מקומי אותנטי",
        "recommendationSource": "Travel Fish / Local",
        "recommendationSourceUrl": "https://www.travelfish.org/eatandmeet/thailand/eastern_thailand/trat/ko_chang/eat",
        "priceLevel": "$$", "cuisine": "Thai Seafood",
        "vibe": "Fishing village pier, authentic",
        "bestTime": "Lunch / Dinner",
        "googleRating": 4.3, "reviewCount": 410,
        "tags": ["Bang Bao", "Pier", "Authentic"],
    },
    {
        "name": "The Sunflower (Klong Prao)",
        "description": "מסעדה צמחונית/בריאות בקלונג פראו — סלטים, מיצים, סמותי באולס. מקום קטן וחביב לימי בריאות.",
        "location": "Klong Prao Beach, Ko Chang, Trat 23170, Thailand",
        "lat": 12.0517, "lng": 102.3075,
        "categoryTitle": "בתי קפה וקינוחים",
        "recommendationSource": "Travel Fish / Local recs",
        "recommendationSourceUrl": "https://www.travelfish.org/eatandmeet/thailand/eastern_thailand/trat/ko_chang/eat",
        "priceLevel": "$$", "cuisine": "Vegetarian / Healthy",
        "vibe": "Health food, small",
        "bestTime": "Breakfast / Lunch",
        "googleRating": 4.5, "reviewCount": 290,
        "tags": ["Vegetarian", "Health", "Smoothie Bowls"],
    },
]


KOHCHANG_ATTRACTIONS = [
    # --- Outdoor & Adventure (the main family for Koh Chang) ---
    {
        "name": "HTMS Chang Shipwreck Dive Site",
        "description": "ספינת המלחמה הגדולה ביותר ששקעה בתאילנד — שוכן עומק 15-30 מ', אטרקציה מרכזית לצוללנים. עולם תת-מימי שלם בתוך הספינה.",
        "location": "Off west coast of Ko Chang, Trat 23170, Thailand",
        "lat": 12.0500, "lng": 102.2400,
        "categoryTitle": "אקסטרים ופעילויות",
        "recommendationSource": "BB Divers / Thailand Magazine",
        "recommendationSourceUrl": "https://bbdivers.com/koh-chang/snorkeling-trips/",
        "type": "Dive Site (Shipwreck)", "activity_type": "Diving",
        "duration": "Half day (boat trip)", "price": "3,500 THB (2 dives)",
        "costNumeric": 3500,
        "best_time_to_visit": "Morning",
        "rating": 4.7, "reviewCount": 320,
        "tags": ["Dive Site", "Wreck", "Largest in Thailand", "Adventure"],
    },
    {
        "name": "Koh Rang Pinnacle (Hin Gue Daeng)",
        "description": "פינאקל קתדרלי מתחת לים — דגי קיסר, עטלפי-ים, פאפר-פיש, ברקודות. אחד מאתרי הצלילה הכי טובים באזור, חלק מהפארק הימי קוה ראנג.",
        "location": "Koh Rang National Marine Park, off Ko Chang, Trat 23170, Thailand",
        "lat": 11.8233, "lng": 102.3611,
        "categoryTitle": "אקסטרים ופעילויות",
        "recommendationSource": "BB Divers / Koh Chang Dive Guide",
        "recommendationSourceUrl": "https://bbdivers.com/koh-chang/snorkeling-trips/",
        "type": "Dive Site (Pinnacle)", "activity_type": "Diving",
        "duration": "Half day", "price": "3,500 THB (2 dives)",
        "costNumeric": 3500,
        "best_time_to_visit": "Morning",
        "rating": 4.7, "reviewCount": 240,
        "tags": ["Dive Site", "Pinnacle", "Koh Rang", "Marine Park"],
    },
    {
        "name": "Mae Klang Waterfall",
        "description": "מפל קטן ושקט בקצה הכפר — לא חזק כמו האחרים אבל הכי ציורי, ומקומיים לא באים לכאן. תזכיר 5 דקות הליכה מהכביש הראשי.",
        "location": "Near main village, Ko Chang, Trat 23170, Thailand",
        "lat": 12.0925, "lng": 102.3450,
        "categoryTitle": "טבע ונופים",
        "recommendationSource": "I Am Koh Chang / Off-beaten-path",
        "recommendationSourceUrl": "https://iamkohchang.com/activities/best-views-sights.html",
        "type": "Waterfall", "activity_type": "Nature",
        "duration": "1 hour", "price": "Free",
        "costNumeric": 0,
        "best_time_to_visit": "Morning",
        "rating": 4.2, "reviewCount": 180,
        "tags": ["Waterfall", "Hidden", "Quiet"],
    },
    {
        "name": "Mountain Viewpoint (North Koh Chang)",
        "description": "תצפית פנורמית בצפון האי לאורך הדרך הראשית — מבט על אזורי החוף וההרים הפראיים. עצירה חובה בנסיעה.",
        "location": "Main road north Ko Chang, Trat 23170, Thailand",
        "lat": 12.0925, "lng": 102.2920,
        "categoryTitle": "אתרי חובה",
        "recommendationSource": "I Am Koh Chang Best Views",
        "recommendationSourceUrl": "https://iamkohchang.com/activities/best-views-sights.html",
        "type": "Viewpoint", "activity_type": "Sightseeing",
        "duration": "20 mins", "price": "Free",
        "costNumeric": 0,
        "best_time_to_visit": "Sunset",
        "rating": 4.4, "reviewCount": 850,
        "tags": ["Viewpoint", "Free", "Sunset"],
    },
    {
        "name": "Long Beach (Had Sai Yao)",
        "description": "חוף ארוך וחבוי במזרח האי — דקות מאוכלסים, חול לבן, מים שקופים, אווירת off-the-beaten-path. דורש 4WD או הליכה.",
        "location": "East coast Ko Chang, Trat 23170, Thailand",
        "lat": 11.9505, "lng": 102.3830,
        "categoryTitle": "חופים ומים",
        "recommendationSource": "Adventures of Jellie / Off-the-beaten-path",
        "recommendationSourceUrl": "https://www.adventuresofjellie.com/thailand/koh-chang-guide",
        "type": "Hidden Beach", "activity_type": "Beach",
        "duration": "Half day", "price": "Free",
        "costNumeric": 0,
        "best_time_to_visit": "Day",
        "rating": 4.6, "reviewCount": 540,
        "tags": ["Hidden Beach", "East Coast", "Quiet"],
    },
    {
        "name": "Salak Phet Mangrove Forest Walk",
        "description": "שביל מנגרובים מרהיב בקצה הדרום-מזרחי של האי — שביל עץ דרך עצי מנגרובים, ציפורים ימיות, חוויית טבע יוצאת דופן. שונה מהמנגרובים בצפון האי.",
        "location": "Salak Phet Bay, Ko Chang, Trat 23170, Thailand",
        "lat": 11.9510, "lng": 102.3950,
        "categoryTitle": "טבע ונופים",
        "recommendationSource": "Nomadic Matt Koh Chang Guide",
        "recommendationSourceUrl": "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/ko-chang/",
        "type": "Mangrove Forest", "activity_type": "Nature",
        "duration": "1.5 hours", "price": "Free",
        "costNumeric": 0,
        "best_time_to_visit": "Morning",
        "rating": 4.5, "reviewCount": 380,
        "tags": ["Mangrove", "East Coast", "Hidden"],
    },
    {
        "name": "Klong Prao River SUP / Kayak",
        "description": "שייט בקאיאק או SUP במעלה נהר Klong Prao — מים שקטים, מנגרובים מימין ומשמאל, ציפורים. אטרקציה רכה למשפחות.",
        "location": "Klong Prao River, Ko Chang, Trat 23170, Thailand",
        "lat": 12.0530, "lng": 102.3210,
        "categoryTitle": "אקסטרים ופעילויות",
        "recommendationSource": "Koh Chang activity operators",
        "recommendationSourceUrl": "https://iamkohchang.com/activities/snorkelling-trips.html",
        "type": "Kayak / SUP", "activity_type": "Water Sports",
        "duration": "2 hours", "price": "500 THB",
        "costNumeric": 500,
        "best_time_to_visit": "Morning",
        "rating": 4.6, "reviewCount": 290,
        "tags": ["Kayak", "SUP", "River", "Family"],
    },
    {
        "name": "Koh Chang Thai Cooking Class",
        "description": "שיעורי בישול תאי בקלונג פראו — ביקור בשוק, הכנת 4 מנות תאי קלאסיות, אכילה משותפת. חוויה משפחתית מצוינת.",
        "location": "Klong Prao, Ko Chang, Trat 23170, Thailand",
        "lat": 12.0510, "lng": 102.3110,
        "categoryTitle": "למשפחות וילדים",
        "recommendationSource": "Klook / Local cooking schools",
        "recommendationSourceUrl": "https://www.klook.com/",
        "type": "Cooking Class", "activity_type": "Education",
        "duration": "4 hours", "price": "1,500 THB",
        "costNumeric": 1500,
        "best_time_to_visit": "Morning",
        "rating": 4.8, "reviewCount": 420,
        "tags": ["Cooking Class", "Family", "Market Tour"],
    },
    {
        "name": "Koh Yuak Snorkeling Spot",
        "description": "אי קטן מול קוה צ'אנג — שונית מצוינת לסנורקלינג, מים בהירים, פחות מבקרים מ-Koh Rang. שעתיים בסירה.",
        "location": "Koh Yuak (near Ko Chang), Trat 23170, Thailand",
        "lat": 11.9333, "lng": 102.3100,
        "categoryTitle": "אקסטרים ופעילויות",
        "recommendationSource": "Coco Dee Bo / Koh Chang Snorkel Trips",
        "recommendationSourceUrl": "https://cocodeebokohchang.com/activity/snorkeling",
        "type": "Snorkeling Spot", "activity_type": "Water Sports",
        "duration": "Half day", "price": "800 THB (boat trip)",
        "costNumeric": 800,
        "best_time_to_visit": "Morning",
        "rating": 4.5, "reviewCount": 320,
        "tags": ["Snorkeling", "Day Trip", "Koh Yuak"],
    },
    {
        "name": "Trat Old Town Day Trip",
        "description": "טיול ליום שלם לטראט (היבשת) — רחוב קטן עם בתים מורשת מעץ, שווקים מקומיים, אוכל אותנטי. פירוש לאי בלי כפכפי תיירים.",
        "location": "Trat City (mainland, 1h boat + 30min taxi from Ko Chang), Thailand",
        "lat": 12.2434, "lng": 102.5151,
        "categoryTitle": "פינות נסתרות",
        "recommendationSource": "Lonely Planet / TAT",
        "recommendationSourceUrl": "https://www.tourismthailand.org",
        "type": "Heritage Town", "activity_type": "Culture",
        "duration": "Full day", "price": "Transport only",
        "best_time_to_visit": "Day trip",
        "rating": 4.3, "reviewCount": 1100,
        "tags": ["Day Trip", "Heritage", "Mainland", "Authentic"],
    },
    {
        "name": "Khao Salak Phet Mountain Hike",
        "description": "הר 744 מטר במזרח האי — טיול הליכה של 3-4 שעות דרך ג'ונגל לעמדת תצפית. מסלול לא קל אבל הנוף בקצה שווה.",
        "location": "Salak Phet area, Ko Chang, Trat 23170, Thailand",
        "lat": 11.9620, "lng": 102.4042,
        "categoryTitle": "אקסטרים ופעילויות",
        "recommendationSource": "Local hiking guides / AllTrails",
        "recommendationSourceUrl": "https://www.alltrails.com",
        "type": "Mountain Hike", "activity_type": "Hiking",
        "duration": "4 hours", "price": "Free (with guide ~1,000 THB)",
        "best_time_to_visit": "Early morning",
        "rating": 4.5, "reviewCount": 140,
        "tags": ["Hiking", "Adventure", "Jungle", "Viewpoint"],
    },
    {
        "name": "Mu Ko Chang National Park Viewpoint (NP HQ Trail)",
        "description": "תצפית לסיף הסערה היערות והאיים הקטנים — שביל פשוט מהמטה הראשי של הפארק הלאומי. נוף עוצר נשימה במזג אוויר טוב.",
        "location": "Mu Ko Chang National Park HQ trail, Ko Chang, Trat 23170, Thailand",
        "lat": 12.0825, "lng": 102.3300,
        "categoryTitle": "טבע ונופים",
        "recommendationSource": "Feastography Koh Chang Guide 2025",
        "recommendationSourceUrl": "https://www.feastographyblog.com/blog/koh-chang-travel-guide",
        "type": "National Park Viewpoint", "activity_type": "Hiking",
        "duration": "1.5 hours", "price": "200 THB park entry",
        "costNumeric": 200,
        "best_time_to_visit": "Morning",
        "rating": 4.5, "reviewCount": 280,
        "tags": ["National Park", "Viewpoint", "Hiking"],
    },
    {
        "name": "Bang Bao Sunset Cruise",
        "description": "שייט סנסט מ-Bang Bao Pier — שייט שעתיים, ארוחת ערב על הסירה, נוף השקיעה על הים. אופציה רומנטית/משפחתית.",
        "location": "Bang Bao Pier, Ko Chang, Trat 23170, Thailand",
        "lat": 11.9690, "lng": 102.3486,
        "categoryTitle": "חופים ומים",
        "recommendationSource": "Koh Chang Activities / Klook",
        "recommendationSourceUrl": "https://www.klook.com/",
        "type": "Sunset Cruise", "activity_type": "Boat Tour",
        "duration": "3 hours", "price": "1,200 THB",
        "costNumeric": 1200,
        "best_time_to_visit": "Late afternoon (16:30 departure)",
        "rating": 4.6, "reviewCount": 980,
        "tags": ["Sunset", "Cruise", "Bang Bao", "Romantic"],
    },
    {
        "name": "Koh Wai Sunrise Spot",
        "description": "אי קטן 30 דק' דרומית מ-Bang Bao — חוף שקט, אם נשארים ללילה, השקיעה והזריחה אגדיות. בקתות צנועות.",
        "location": "Koh Wai (south of Ko Chang), Trat 23170, Thailand",
        "lat": 11.9168, "lng": 102.3712,
        "categoryTitle": "חופים ומים",
        "recommendationSource": "BucketListly / Koh Chang Guide",
        "recommendationSourceUrl": "https://www.bucketlistly.blog/posts/koh-chang-best-things-to-do",
        "type": "Small Island Beach", "activity_type": "Beach / Overnight",
        "duration": "Day trip or overnight", "price": "Boat ~400 THB return",
        "costNumeric": 400,
        "best_time_to_visit": "Day or overnight",
        "rating": 4.6, "reviewCount": 620,
        "tags": ["Koh Wai", "Sunrise", "Quiet"],
    },
    {
        "name": "Salakphet Boat Cooperative (Lunch + Boat Tour)",
        "description": "טיול עצמאי ייחודי — קהילת דייגים בכפר Salakphet מארגנת טיול סירה+ארוחה בכפר. תיירות אחראית, חוויה אותנטית, פחות מתויירת.",
        "location": "Salakphet Fishing Village, Ko Chang, Trat 23170, Thailand",
        "lat": 11.9905, "lng": 102.3855,
        "categoryTitle": "פינות נסתרות",
        "recommendationSource": "Travel Fish / Community-based tourism",
        "recommendationSourceUrl": "https://www.travelfish.org/eatandmeet/thailand/eastern_thailand/trat/ko_chang/eat",
        "type": "Community Boat Tour", "activity_type": "Eco-tourism",
        "duration": "Half day", "price": "1,200 THB",
        "costNumeric": 1200,
        "best_time_to_visit": "Morning",
        "rating": 4.7, "reviewCount": 150,
        "tags": ["Eco-tourism", "Fishing Village", "Authentic", "Salakphet"],
    },
]


# ============================================================================
# MERGE LOGIC
# ============================================================================

ENTRIES_BY_FILE = [
    # per-city restaurants
    ("bangkok-restaurants.json", "restaurants", "Bangkok", BANGKOK_RESTAURANTS),
    ("pattaya-restaurants.json", "restaurants", "Pattaya", PATTAYA_RESTAURANTS),
    ("kohchang-restaurants.json", "restaurants", "Ko Chang", KOHCHANG_RESTAURANTS),
    # per-city attractions
    ("bangkok-attractions.json", "attractions", "Bangkok", BANGKOK_ATTRACTIONS),
    ("pattaya-attractions.json", "attractions", "Pattaya", PATTAYA_ATTRACTIONS),
    ("kohchang-attractions.json", "attractions", "Ko Chang", KOHCHANG_ATTRACTIONS),
]

ALL_FILES = [
    ("all-restaurants.json", "restaurants",
     BANGKOK_RESTAURANTS + PATTAYA_RESTAURANTS + KOHCHANG_RESTAURANTS),
    ("all-attractions.json", "attractions",
     BANGKOK_ATTRACTIONS + PATTAYA_ATTRACTIONS + KOHCHANG_ATTRACTIONS),
]


def existing_names(entries: list[dict]) -> set[str]:
    out = set()
    for e in entries:
        n = (e.get("name") or "").strip().lower()
        if n:
            out.add(n)
    return out


def geocode_and_normalize(entry: dict, city: str) -> dict:
    """Try to refine lat/lng via Photon; always set googleMapsUrl from final coords."""
    name = entry.get("name", "")
    refined = photon_search(name, city)
    if refined:
        entry["lat"] = round(refined["lat"], 6)
        entry["lng"] = round(refined["lng"], 6)
        print(f"    [Photon ✓] {name} → {entry['lat']},{entry['lng']}")
    else:
        # Keep approximate coords
        print(f"    [Photon —] {name} (kept approximate {entry['lat']},{entry['lng']})")
    entry["googleMapsUrl"] = gmaps_url(entry["lat"], entry["lng"])
    time.sleep(0.6)  # be gentle on Photon's free service
    return entry


def append_to_file(path: Path, key: str, new_entries: list[dict], city: str) -> tuple[int, int]:
    if not path.exists():
        print(f"  ! Missing file: {path}")
        return (0, 0)
    data = json.loads(path.read_text(encoding="utf-8"))
    existing = data.get(key) or []
    existing_set = existing_names(existing)
    added = 0
    skipped = 0
    for entry in new_entries:
        name = (entry.get("name") or "").strip()
        if name.lower() in existing_set:
            print(f"    [skip dup] {name}")
            skipped += 1
            continue
        # geocode now
        normalized = geocode_and_normalize(dict(entry), city)
        existing.append(normalized)
        existing_set.add(name.lower())
        added += 1
    data[key] = existing
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    return (added, skipped)


def append_to_all_file(path: Path, key: str, new_entries: list[dict]) -> tuple[int, int]:
    """Append to all-*.json. These already had per-city geocoding, so just dedup & merge."""
    if not path.exists():
        print(f"  ! Missing file: {path}")
        return (0, 0)
    data = json.loads(path.read_text(encoding="utf-8"))
    existing = data.get(key) or []
    existing_set = existing_names(existing)
    added = 0
    skipped = 0
    for entry in new_entries:
        name = (entry.get("name") or "").strip()
        if name.lower() in existing_set:
            skipped += 1
            continue
        # entry already has refined coords from the per-city pass
        existing.append(entry)
        existing_set.add(name.lower())
        added += 1
    data[key] = existing
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    return (added, skipped)


def main():
    print(f"=== Phase 0 manual bootstrap — adding new entries ===\n")
    total_added = 0
    total_skipped = 0

    # First pass: per-city files (geocoding happens here)
    for filename, key, city, entries in ENTRIES_BY_FILE:
        path = HERE / filename
        print(f"\n--- {filename} ({city}, {len(entries)} candidates) ---")
        added, skipped = append_to_file(path, key, entries, city)
        print(f"  Added: {added}, skipped (dup): {skipped}")
        total_added += added
        total_skipped += skipped

    # Second pass: re-read per-city files to get geocoded entries, then merge into all-*.json
    print(f"\n=== Rebuilding all-*.json from per-city files (with refined coords) ===\n")
    for all_filename, key, _new_entries in ALL_FILES:
        all_path = HERE / all_filename
        # Read all per-city files of this key
        merged: list[dict] = []
        seen: set[str] = set()
        for filename, k, _city, _entries in ENTRIES_BY_FILE:
            if k != key:
                continue
            per_path = HERE / filename
            if not per_path.exists():
                continue
            per_data = json.loads(per_path.read_text(encoding="utf-8"))
            for e in per_data.get(key, []):
                n = (e.get("name") or "").strip().lower()
                if n and n not in seen:
                    seen.add(n)
                    merged.append(e)
        all_data = {key: merged}
        all_path.write_text(json.dumps(all_data, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"  {all_filename}: {len(merged)} total entries")

    print(f"\n=== Done. Added {total_added} new entries total, skipped {total_skipped} dups. ===")


if __name__ == "__main__":
    main()


